language: java
sudo: false # faster builds
before_install:
  - chmod +x mvnw
script: "mvn clean install"
jdk:
  - openjdk8
branches:
  only:
  - release
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  skip-cleanup: true
  keep-history: true
  app: perisperis
  on:
    branch: release
