language: java
sudo: false # faster builds
before_install:
  - chmod +x mvnw
script: "mvn clean install"
jdk:
  - openjdk8
branches:
  only:
  - release
  
  
language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
